### ISSUE TITLE
issue with PCBWay_drill

### ISSUE THREAD

**Issue by geoffreymbrown** [INTI-CMNB/kicad-ci-test-spora#1]
I had an issue with the PCBWay config file -- specifically the drill configuration

     left_digits: 3
     right_digits: 3

This seems to lead to strange scaling issues.  I think it should be

     left_digits: 2
     right_digits: 4

I finally found the issue by looking at this https://docs.oshpark.com/design-tools/gerbv/fix-drill-format/  which discusses the problems with imperial unit drill files.

**Comment by set-soft** [comment]
Hi @geoffreymbrown !
Thanks for reporting. I adjusted it.
